### ISSUE TITLE
garbage and duplicates

### ISSUE THREAD

**Issue by thierryH91200** [richardfrk/EricsMark#1]
You do not think that if you run twice the extension EricsMark there will be duplicates it would be nice to do a cleaning before this style otherwise the idea is good

    func perform(with invocation: XCSourceEditorCommandInvocation, completionHandler: @escaping (Error?) -> Void ) -> Void
    {
        var lineClassMark:Int?
        var linePropertieMark:Int?
        var lineIBOutletMark:Int?
        var lineSuperMethodMark:Int?
        var lineIBActionMark:Int?
        var linePrivateMethodMark:Int?
        var lineExtensionMark:Int?
        
        var bRemove  = true
        let array = ["//MARK: - IBOutlets","//MARK: - Properties","//MARK: - Super Methods","//MARK: - Private Methods","//MARK: - Extensions","//MARK: - IBActions"]
        while ( bRemove == true)
        {
            bRemove = false
            for i in 0..<invocation.buffer.lines.count
            {
                let line = invocation.buffer.lines[i] as! String
        
                if array.contains(line) == true
                {
                    invocation.buffer.lines.removeObject(at: i)
                    bRemove = true
                    break
                }
            }
        }
....

**Comment by thierryH91200** [comment]
no it 's not good

```
    var bRemove  = true
    let array = ["//MARK: - IBOutlets","//MARK: - Properties","//MARK: - Super Methods","//MARK: - Private Methods","//MARK: - Extensions","//MARK: - IBActions"]
    while ( bRemove == true)
    {
        bRemove = false
        for i in 0..<invocation.buffer.lines.count
        {
            let line = invocation.buffer.lines[i] as! String

            if line.contains(array[0])  || line.contains(array[1]) || line.contains(array[2]) || line.contains(array[3]) || line.contains(array[4]) || line.contains(array[5])
            {
                invocation.buffer.lines.removeObject(at: i)
                bRemove = true
                break
            }
        }
    }
```

**Comment by richardfrk** [comment]
Hi thierryH91200, it is a good idea. I was wondering about this, send me a pull request.
